# Cyclospora outbreak

## CDC Surveillance data

In [1]:
import requests
from bs4 import BeautifulSoup
from playwright.async_api import async_playwright
import pandas as pd
import re

In [2]:
playwright = await async_playwright().start()
browser = await playwright.chromium.launch(headless=True)

In [3]:
page = await browser.new_page()

In [4]:
await page.goto("https://www.cdc.gov/cyclosporiasis/php/surveillance/index.html")

In [5]:
async with page.expect_download() as download_info:
    await page.click('a[aria-label="Download this data in a CSV file format."]')

download = await download_info.value
await download.save_as("data/data.csv")
print("Downloaded to:", await download.path())

Downloaded to: /tmp/playwright-artifacts-nv86jX/1393f14c-981f-44fe-b0aa-f2a0fe99253a

In [6]:
df = pd.read_csv("data/data.csv")

In [7]:
df.head()

     Location Number of Sick People
0     Alabama               1 to 49
1      Alaska               1 to 49
2     Arizona               1 to 49
3    Arkansas             50 to 199
4  California               1 to 49

In [8]:
df = df[df['Location'] != 'Michigan']

In [9]:
df

                Location Number of Sick People
0                Alabama               1 to 49
1                 Alaska               1 to 49
2                Arizona               1 to 49
3               Arkansas             50 to 199
4             California               1 to 49
5               Colorado               1 to 49
6            Connecticut               1 to 49
7   District of Columbia               1 to 49
8                Florida             50 to 199
9                Georgia             50 to 199
10                 Idaho               1 to 49
11              Illinois            500 to 999
12               Indiana            500 to 999
13                  Iowa             50 to 199
14                Kansas            200 to 499
15              Kentucky            200 to 499
16             Louisiana             50 to 199
17                 Maine               1 to 49
18              Maryland             50 to 199
19         Massachusetts             50 to 199
21             Minnesota             50 to 199
22           Mississippi               1 to 49
23              Missouri             50 to 199
24               Montana               1 to 49
25              Nebraska            200 to 499
26                Nevada               1 to 49
27         New Hampshire             50 to 199
28            New Jersey             50 to 199
29              New York            200 to 499
30        North Carolina            500 to 999
31          North Dakota               1 to 49
32                  Ohio          1000 to 3999
33              Oklahoma            200 to 499
34                Oregon               1 to 49
35          Pennsylvania            200 to 499
36           Puerto Rico               1 to 49
37          Rhode Island               1 to 49
38        South Carolina               1 to 49
39          South Dakota               1 to 49
40             Tennessee             50 to 199
41                 Texas            200 to 499
42                  Utah               1 to 49
43               Vermont               1 to 49
44              Virginia             50 to 199
45            Washington               1 to 49
46         West Virginia             50 to 199
47             Wisconsin             50 to 199
48               Wyoming               1 to 49

In [10]:
df['min'] = df['Number of Sick People'].str.extract(r'(\d+)\s+to\s+\d+').astype(int)
df['max'] = df['Number of Sick People'].str.extract(r'\d+\s+to\s+(\d+)').astype(int)

In [11]:
df['average'] = df[['min', 'max']].mean(axis=1)

In [12]:
df.sort_values(by='average', ascending=False, inplace=True)
df.head()

          Location Number of Sick People   min   max  average
32            Ohio          1000 to 3999  1000  3999   2499.5
12         Indiana            500 to 999   500   999    749.5
30  North Carolina            500 to 999   500   999    749.5
11        Illinois            500 to 999   500   999    749.5
25        Nebraska            200 to 499   200   499    349.5

In [13]:
df.to_csv("data/clean_data.csv", index=False)

### Cyclospora confirmed cases and notes

In [14]:
# await page.goto("https://www.cdc.gov/cyclosporiasis/php/surveillance/index.html")

In [15]:
# fast_facts = await page.locator('div.dfe-section[data-section="cdc_generic_section_3"]').inner_text()
# print(fast_facts)

In [16]:
# fast_facts

In [17]:
# labels = ['last_updated', 'total_cases', 'hospitalizations', 'deaths', 'states_reporting']

# as_of_text = await page.locator('div.dfe-section[data-section="cdc_generic_section_3"] p').inner_text()

# as_of_date = re.search(r'As of (.+?):', as_of_text).group(1).strip()

# items = await page.locator('div.dfe-section[data-section="cdc_generic_section_3"] ul.nested-list li').all()

# values = [as_of_date] + [((await item.inner_text()).split(':')[1].strip()) for item in items]

# cdc_data = dict(zip(labels, values))
# print(cdc_data)

In [18]:
# df_cdc = pd.DataFrame([cdc_data])

In [19]:
# df_cdc.to_csv("data/cdc_notes.csv", index=False)

### Add last updated to CDC data

In [20]:
# df['Last Updated'] = df_cdc['last_updated'][0]

In [21]:
df['Last Updated'] = "May 1 - July 27, 2026"

In [22]:
df

,Location,Number of Sick People,min,max,average,Last Updated
32,Ohio,1000 to 3999,1000,3999,2499.5,"May 1 - July 27, 2026"
12,Indiana,500 to 999,500,999,749.5,"May 1 - July 27, 2026"
30,North Carolina,500 to 999,500,999,749.5,"May 1 - July 27, 2026"
11,Illinois,500 to 999,500,999,749.5,"May 1 - July 27, 2026"
25,Nebraska,200 to 499,200,499,349.5,"May 1 - July 27, 2026"
29,New York,200 to 499,200,499,349.5,"May 1 - July 27, 2026"
15,Kentucky,200 to 499,200,499,349.5,"May 1 - July 27, 2026"
14,Kansas,200 to 499,200,499,349.5,"May 1 - July 27, 2026"
41,Texas,200 to 499,200,499,349.5,"May 1 - July 27, 2026"
33,Oklahoma,200 to 499,200,499,349.5,"May 1 - July 27, 2026"
35,Pennsylvania,200 to 499,200,499,349.5,"May 1 - July 27, 2026"
16,Louisiana,50 to 199,50,199,124.5,"May 1 - July 27, 2026"
3,Arkansas,50 to 199,50,199,124.5,"May 1 - July 27, 2026"
13,Iowa,50 to 199,50,199,124.5,"May 1 - July 27, 2026"
9,Georgia,50 to 199,50,199,124.5,"May 1 - July 27, 2026"
8,Florida,50 to 199,50,199,124.5,"May 1 - July 27, 2026"
44,Virginia,50 to 199,50,199,124.5,"May 1 - July 27, 2026"
47,Wisconsin,50 to 199,50,199,124.5,"May 1 - July 27, 2026"
23,Missouri,50 to 199,50,199,124.5,"May 1 - July 27, 2026"
46,West Virginia,50 to 199,50,199,124.5,"May 1 - July 27, 2026"
40,Tennessee,50 to 199,50,199,124.5,"May 1 - July 27, 2026"
18,Maryland,50 to 199,50,199,124.5,"May 1 - July 27, 2026"
19,Massachusetts,50 to 199,50,199,124.5,"May 1 - July 27, 2026"
21,Minnesota,50 to 199,50,199,124.5,"May 1 - July 27, 2026"
27,New Hampshire,50 to 199,50,199,124.5,"May 1 - July 27, 2026"
28,New Jersey,50 to 199,50,199,124.5,"May 1 - July 27, 2026"
1,Alaska,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
2,Arizona,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
4,California,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
5,Colorado,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
6,Connecticut,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
7,District of Columbia,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
10,Idaho,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
0,Alabama,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
31,North Dakota,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
24,Montana,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
17,Maine,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
26,Nevada,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
22,Mississippi,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
34,Oregon,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
39,South Dakota,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
38,South Carolina,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
37,Rhode Island,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
36,Puerto Rico,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
43,Vermont,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
42,Utah,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
45,Washington,1 to 49,1,49,25.0,"May 1 - July 27, 2026"
48,Wyoming,1 to 49,1,49,25.0,"May 1 - July 27, 2026"

# Local CDC Data

## Michigan

### First, drop duplicate data from CDC

In [23]:
states_to_drop = ['Michigan', 'Alabama', 'Ohio', 'Louisiana','Indiana', 'Maryland', 'Mississippi']

df = df.drop(df[df['Location'].isin(states_to_drop)].index)

In [24]:
df.head()

,Location,Number of Sick People,min,max,average,Last Updated
30,North Carolina,500 to 999,500,999,749.5,"May 1 - July 27, 2026"
11,Illinois,500 to 999,500,999,749.5,"May 1 - July 27, 2026"
25,Nebraska,200 to 499,200,499,349.5,"May 1 - July 27, 2026"
29,New York,200 to 499,200,499,349.5,"May 1 - July 27, 2026"
15,Kentucky,200 to 499,200,499,349.5,"May 1 - July 27, 2026"

In [25]:
await page.goto("https://www.michigan.gov/mdhhs/keep-mi-healthy/infectious-diseases/infectious-disease-outbreaks")

<Response url='https://www.michigan.gov/mdhhs/keep-mi-healthy/infectious-diseases/infectious-disease-outbreaks' request=<Request url='https://www.michigan.gov/mdhhs/keep-mi-healthy/infectious-diseases/infectious-disease-outbreaks' method='GET'>>

In [26]:
total_cases = await page.inner_text('p:has(strong:text("Total Cases:"))')
print(total_cases)

Total Cases: 14,277
Hospitalizations: As of August 20, 2026, 335 reported cases indicated they had been hospitalized.
Deaths: 2

In [27]:
match = re.search(r'Total Cases:\s*([\d,]+)', total_cases)
cases = match.group(1) 

michigan_cases = int(cases.replace(',', '')) 

print(cases)     
print(michigan_cases)

14,277
14277

In [28]:
deaths = re.search(r'Deaths:\s*([\d,]+)', total_cases)
deaths_count = deaths.group(1)

print(deaths_count)

2

In [29]:
last_updated = await page.inner_text('p:has(strong:text("Last updated:"))')
date_match = re.search(r'(\w+ \d+, \d{4})', last_updated)
last_updated_Michigan = date_match.group(1) if date_match else None
print(last_updated_Michigan)

August 20, 2026

## Add local Michigan data

In [30]:
df.head()

,Location,Number of Sick People,min,max,average,Last Updated
30,North Carolina,500 to 999,500,999,749.5,"May 1 - July 27, 2026"
11,Illinois,500 to 999,500,999,749.5,"May 1 - July 27, 2026"
25,Nebraska,200 to 499,200,499,349.5,"May 1 - July 27, 2026"
29,New York,200 to 499,200,499,349.5,"May 1 - July 27, 2026"
15,Kentucky,200 to 499,200,499,349.5,"May 1 - July 27, 2026"

In [31]:
new_row = {
    'Location': 'Michigan',
    'Number of Sick People': michigan_cases,
    'min': michigan_cases,
    'max': michigan_cases,
    'average': michigan_cases,
    'Last Updated': last_updated_Michigan,
    'deaths': deaths_count

}

df_local = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

In [32]:
df_local['deaths'] = df_local['deaths'].fillna(0).astype(int)

In [33]:
df_local

,Location,Number of Sick People,min,max,average,Last Updated,deaths
0,North Carolina,500 to 999,500,999,749.5,"May 1 - July 27, 2026",0
1,Illinois,500 to 999,500,999,749.5,"May 1 - July 27, 2026",0
2,Nebraska,200 to 499,200,499,349.5,"May 1 - July 27, 2026",0
3,New York,200 to 499,200,499,349.5,"May 1 - July 27, 2026",0
4,Kentucky,200 to 499,200,499,349.5,"May 1 - July 27, 2026",0
5,Kansas,200 to 499,200,499,349.5,"May 1 - July 27, 2026",0
6,Texas,200 to 499,200,499,349.5,"May 1 - July 27, 2026",0
7,Oklahoma,200 to 499,200,499,349.5,"May 1 - July 27, 2026",0
8,Pennsylvania,200 to 499,200,499,349.5,"May 1 - July 27, 2026",0
9,Arkansas,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
10,Iowa,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
11,Georgia,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
12,Florida,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
13,Virginia,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
14,Wisconsin,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
15,Missouri,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
16,West Virginia,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
17,Tennessee,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
18,Massachusetts,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
19,Minnesota,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
20,New Hampshire,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
21,New Jersey,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
22,Alaska,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
23,Arizona,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
24,California,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
25,Colorado,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
26,Connecticut,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
27,District of Columbia,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
28,Idaho,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
29,North Dakota,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
30,Montana,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
31,Maine,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
32,Nevada,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
33,Oregon,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
34,South Dakota,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
35,South Carolina,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
36,Rhode Island,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
37,Puerto Rico,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
38,Vermont,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
39,Utah,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
40,Washington,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
41,Wyoming,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
42,Michigan,14277,14277,14277,14277.0,"August 20, 2026",2

## Alabama

In [34]:
# await page.goto("https://www.alabamapublichealth.gov/infectiousdiseases/cases.html")

In [35]:
# await page.wait_for_load_state("networkidle", timeout=30000)

### Manually adding Alabama data

In [36]:
# df_local.head()

In [37]:
# alabama = pd.DataFrame([{"Location": "Alabama", "Number of Sick People": 2, "min": 2, "max": 2, "average": 2, "Last Updated": "July 15, 2026"}])

In [38]:
# df_local = pd.concat([df_local, alabama], ignore_index=True)

In [39]:
# df_local

In [40]:
# df_local.to_csv("data/clean_data_local.csv", index=False)

## Add local stations data on the Sheet

In [41]:
sheet_id = "14INvC79GAOzaEdB_9mRztD7Mw_PDLlYYMwVVAB3e_-k"
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv"

In [42]:
stations = pd.read_csv(url)

In [43]:
stations

,Location,Number of Sick People,min,max,average,Last Updated,deaths
0,Ohio,4087,4087,4087,4087,"July 28, 2026",0
1,Louisiana,100,100,100,100,"July 28, 2026",0
2,Alabama,33,33,33,33,"August 3, 2026",0
3,Indiana,1349,1349,1349,1349,"August 3, 2026",0
4,Maryland,69,69,69,69,"July 14, 2026",0
5,Florida,254,254,254,254,"July 25, 2026",0
6,Mississippi,5,5,5,5,"July 16, 2026",0

In [44]:
df_local = pd.concat([df_local, stations], ignore_index=True)

In [45]:
df_local

,Location,Number of Sick People,min,max,average,Last Updated,deaths
0,North Carolina,500 to 999,500,999,749.5,"May 1 - July 27, 2026",0
1,Illinois,500 to 999,500,999,749.5,"May 1 - July 27, 2026",0
2,Nebraska,200 to 499,200,499,349.5,"May 1 - July 27, 2026",0
3,New York,200 to 499,200,499,349.5,"May 1 - July 27, 2026",0
4,Kentucky,200 to 499,200,499,349.5,"May 1 - July 27, 2026",0
5,Kansas,200 to 499,200,499,349.5,"May 1 - July 27, 2026",0
6,Texas,200 to 499,200,499,349.5,"May 1 - July 27, 2026",0
7,Oklahoma,200 to 499,200,499,349.5,"May 1 - July 27, 2026",0
8,Pennsylvania,200 to 499,200,499,349.5,"May 1 - July 27, 2026",0
9,Arkansas,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
10,Iowa,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
11,Georgia,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
12,Florida,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
13,Virginia,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
14,Wisconsin,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
15,Missouri,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
16,West Virginia,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
17,Tennessee,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
18,Massachusetts,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
19,Minnesota,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
20,New Hampshire,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
21,New Jersey,50 to 199,50,199,124.5,"May 1 - July 27, 2026",0
22,Alaska,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
23,Arizona,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
24,California,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
25,Colorado,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
26,Connecticut,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
27,District of Columbia,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
28,Idaho,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
29,North Dakota,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
30,Montana,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
31,Maine,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
32,Nevada,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
33,Oregon,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
34,South Dakota,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
35,South Carolina,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
36,Rhode Island,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
37,Puerto Rico,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
38,Vermont,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
39,Utah,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
40,Washington,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
41,Wyoming,1 to 49,1,49,25.0,"May 1 - July 27, 2026",0
42,Michigan,14277,14277,14277,14277.0,"August 20, 2026",2
43,Ohio,4087,4087,4087,4087.0,"July 28, 2026",0
44,Louisiana,100,100,100,100.0,"July 28, 2026",0
45,Alabama,33,33,33,33.0,"August 3, 2026",0
46,Indiana,1349,1349,1349,1349.0,"August 3, 2026",0
47,Maryland,69,69,69,69.0,"July 14, 2026",0
48,Florida,254,254,254,254.0,"July 25, 2026",0
49,Mississippi,5,5,5,5.0,"July 16, 2026",0

In [46]:
df_local.to_csv("data/clean_data_local.csv", index=False)